# Usa la imagen oficial de MongoDB como base
FROM mongo:latest

# Establece una variable de entorno para el nombre de la base de datos
ENV MONGO_INITDB_DATABASE=portafolio

# Exponer el puerto de MongoDB
EXPOSE 27017

# Comando para iniciar MongoDBs
CMD ["mongod"]
