version: '3.8'
name: 'blogprod'

services:
  client:
    build: 
      context: ./
      dockerfile: client/Dockerfile
    container_name: vite-client-prod
    volumes:
      - ./client:/src/client
    ports:
      - "5170:5173"
    depends_on:
      - app

  app:
    build: 
      context: ./
      dockerfile: server/Dockerfile
    container_name: express-app-prod
    volumes:
      - ./server:/src/server
    ports:
      - "3030:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:54328/mydatabase

  db:
    image: postgres:latest
    container_name: postgres-db-prod
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: blog_password
    ports:
      - "54328:5432"
volumes:
  postgres_data:


  
