version: '3.8'
name: 'blog'

services:
  client:
    build: 
      context: ./
      dockerfile: client/Dockerfile
    container_name: vite-client
    volumes:
    - ./client:/src/client
    ports:
      - "5170:5173"
    depends_on:
      - app

  app:
    build: 
      context: ./
      dockerfile: server/Dockerfile
    container_name: express-app
    volumes:
      - ./server:/src/server
    ports:
      - "3030:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:54328/mydatabase

  db:
    build:
      context: ./
      dockerfile: database/Dockerfile
    container_name: mysql-db
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: blog_db
      MYSQL_ROOT_PASSWORD: root_password

      MYSQL_USER: blog_user
      MYSQL_PASSWORD: blog_password

    ports:
      - "33068:3306"


  
